courses:
    - 
        name: Laskennan mallit
        lecturer: Timo Soini
        type: LU
        times:
            - 
                day: mon
                time: 12-14
                location: A111
    
    - 
        name: Laskennan mallit
        lecturer: Jussi Allah-aho
        type: LH
        times:
            - 
                day: wed
                time: 16-18
                location: Eira
                
    - 
        name: C-ohjelmointi
        lecturer: Kimmo Wilska
        type: LU
        times:
            - 
                day: tue
                time: 14-16
                location: CK112
            - 
                day: thu
                time: 10-12
                location: CK112
                
    - 
        name: Algoritmien suunnittelu ja analyysi
        lecturer: Luis Urzúa
        type: LU
        times:
            - 
                day: fri
                time: 8-10
                location: underground
